// 場景主題：天空、霧、光線、後製、地面材質、音效氛圍與配樂
export const THEMES = {
  city: {
    id: 'city',
    vehicle: 'train',
    track: 'rail',
    name: '城市鐵道',
    en: 'CITY LINE',
    swatch: ['#3f86d8', '#f3d9b8'],
    sky: { horizon: '#f3d9b8', zenith: '#3f86d8', glow: '#ffbf73', sunDir: [0.35, 0.16, -1], cloud: 0.85, stars: 0 },
    fog: { color: '#e0c8aa', near: 60, far: 250 },
    hemi: { sky: '#cfe3ff', ground: '#8a7057', intensity: 1.1 },
    sun: { color: '#fff0d6', intensity: 3.1, offset: [-14, 26, 12] },
    exposure: 1.05,
    bloom: 0.45,
    envIntensity: 0.45,
    particles: null,
    ground: { color: '#b4aa9e', roughness: 0.95 },
    ballast: '#9b938a',
    surface: 'gravel',
    reverb: 0.08,
    ambience: 'city',
    music: 'city',
  },
  seaside: {
    id: 'seaside',
    vehicle: 'bus',
    track: 'road',
    name: '海岸線',
    en: 'OCEAN LINE',
    swatch: ['#1fa2e0', '#ffe9b0'],
    sky: { horizon: '#d8f0ff', zenith: '#1f8fe0', glow: '#fff3c4', sunDir: [-0.5, 0.45, -1], cloud: 0.55, stars: 0 },
    fog: { color: '#cde8f5', near: 80, far: 320 },
    hemi: { sky: '#d9f1ff', ground: '#c7a77a', intensity: 1.25 },
    sun: { color: '#fff6e2', intensity: 3.5, offset: [-10, 30, 8] },
    exposure: 1.08,
    bloom: 0.4,
    envIntensity: 0.55,
    particles: null,
    ground: { color: '#d8c7a6', roughness: 0.95 },
    ballast: '#b3a38c',
    surface: 'gravel',
    reverb: 0.05,
    ambience: 'seaside',
    music: 'seaside',
  },
  tunnel: {
    id: 'tunnel',
    vehicle: 'train',
    track: 'rail',
    name: '地鐵隧道',
    en: 'UNDERGROUND',
    swatch: ['#1b1f27', '#ffb347'],
    sky: { horizon: '#1a1b20', zenith: '#0c0d11', glow: '#000000', sunDir: [0, 1, 0], cloud: 0, stars: 0 },
    fog: { color: '#15171c', near: 25, far: 150 },
    hemi: { sky: '#8aa4c8', ground: '#3a2e24', intensity: 0.65 },
    sun: { color: '#ffd9a0', intensity: 1.6, offset: [0, 30, 1] },
    exposure: 1.15,
    bloom: 0.75,
    envIntensity: 0.3,
    particles: null,
    ground: { color: '#6f675e', roughness: 0.9 },
    ballast: '#6a625a',
    surface: 'gravel',
    reverb: 0.55,
    ambience: 'tunnel',
    music: 'tunnel',
  },
  snow: {
    id: 'snow',
    vehicle: 'plow',
    track: 'snowroad',
    name: '雪山列車',
    en: 'SNOW PEAK',
    swatch: ['#9cc3e6', '#ffffff'],
    sky: { horizon: '#e9f1f8', zenith: '#7fa9d6', glow: '#ffffff', sunDir: [0.6, 0.25, -1], cloud: 0.95, stars: 0 },
    fog: { color: '#dfe8f0', near: 40, far: 230 },
    hemi: { sky: '#e6f0ff', ground: '#b9c6d6', intensity: 1.25 },
    sun: { color: '#f4f8ff', intensity: 2.4, offset: [-12, 24, 14] },
    exposure: 1.0,
    bloom: 0.3,
    envIntensity: 0.5,
    particles: { type: 'snow', color: '#ffffff', size: 0.16 },
    ground: { color: '#f4f8fc', roughness: 0.85, tex: 'snow' },
    ballast: '#c9d2dc',
    surface: 'snow',
    reverb: 0.12,
    ambience: 'snow',
    music: 'snow',
  },
  neon: {
    id: 'neon',
    vehicle: 'hoverbus',
    track: 'neonroad',
    name: '霓虹夜城',
    en: 'NEON NIGHT',
    swatch: ['#1a1240', '#ff3db5'],
    sky: { horizon: '#3a1f5c', zenith: '#07061a', glow: '#ff5fa2', sunDir: [0.2, 0.08, -1], cloud: 0.25, stars: 1 },
    fog: { color: '#2a1845', near: 45, far: 220 },
    hemi: { sky: '#6c5bd9', ground: '#2a1a3a', intensity: 0.75 },
    sun: { color: '#9fb8ff', intensity: 1.1, offset: [12, 26, 10] },
    exposure: 1.2,
    bloom: 0.95,
    envIntensity: 0.6,
    particles: null,
    ground: { color: '#4a4452', roughness: 0.35 },
    ballast: '#3e3946',
    surface: 'wet',
    reverb: 0.2,
    ambience: 'neon',
    music: 'neon',
  },
  desert: {
    id: 'desert',
    vehicle: 'camels',
    track: 'dirt',
    name: '沙漠峽谷',
    en: 'CANYON RUN',
    swatch: ['#e0773a', '#ffd89a'],
    sky: { horizon: '#ffd9a8', zenith: '#3d7fd0', glow: '#ffb347', sunDir: [0.3, 0.35, -1], cloud: 0.2, stars: 0 },
    fog: { color: '#f0c898', near: 70, far: 300 },
    hemi: { sky: '#ffe8c8', ground: '#b0643a', intensity: 1.2 },
    sun: { color: '#ffe3b8', intensity: 3.8, offset: [-12, 30, 10] },
    exposure: 1.05,
    bloom: 0.4,
    envIntensity: 0.45,
    particles: null,
    ground: { color: '#e2b98a', roughness: 1, tex: 'sand' },
    ballast: '#b58d68',
    surface: 'sand',
  },
  sakura: {
    id: 'sakura',
    vehicle: 'floats',
    track: 'stone',
    name: '櫻花古都',
    en: 'SAKURA TOWN',
    swatch: ['#ffb7d0', '#fff4f8'],
    sky: { horizon: '#ffe6ee', zenith: '#6ca8e6', glow: '#ffd2e0', sunDir: [-0.4, 0.3, -1], cloud: 0.6, stars: 0 },
    fog: { color: '#f6dde6', near: 60, far: 260 },
    hemi: { sky: '#ffeef6', ground: '#9a8078', intensity: 1.2 },
    sun: { color: '#fff2ea', intensity: 3.0, offset: [-14, 26, 12] },
    exposure: 1.05,
    bloom: 0.45,
    envIntensity: 0.45,
    particles: { type: 'petals', color: '#ffb3cf', size: 0.24 },
    ground: { color: '#bcb0a4', roughness: 0.95 },
    ballast: '#a39a90',
    surface: 'gravel',
  },
  jungle: {
    id: 'jungle',
    vehicle: 'elephants',
    track: 'mud',
    name: '熱帶雨林',
    en: 'JUNGLE LINE',
    swatch: ['#1f6b3a', '#9be15d'],
    sky: { horizon: '#cfe6c4', zenith: '#5d9fcf', glow: '#fff1b8', sunDir: [0.2, 0.55, -1], cloud: 0.7, stars: 0 },
    fog: { color: '#a9c9a0', near: 30, far: 170 },
    hemi: { sky: '#d8f5c8', ground: '#3e5a2a', intensity: 1.15 },
    sun: { color: '#fff4d0', intensity: 2.6, offset: [-8, 28, 10] },
    exposure: 1.05,
    bloom: 0.5,
    envIntensity: 0.4,
    particles: { type: 'spores', color: '#e8ff9a', size: 0.14 },
    ground: { color: '#7d7a55', roughness: 0.95 },
    ballast: '#7b7462',
    surface: 'grass',
  },
  volcano: {
    id: 'volcano',
    vehicle: 'tortoises',
    track: 'basalt',
    name: '火山熔岩',
    en: 'LAVA LINE',
    swatch: ['#2a1210', '#ff5a1f'],
    sky: { horizon: '#8a3418', zenith: '#140807', glow: '#ff6a2a', sunDir: [0.5, 0.6, -1], cloud: 0.9, stars: 0 },
    fog: { color: '#4a1c12', near: 35, far: 190 },
    hemi: { sky: '#ff9a6a', ground: '#2a1410', intensity: 0.8 },
    sun: { color: '#ffb080', intensity: 1.8, offset: [10, 24, 6] },
    exposure: 1.15,
    bloom: 0.9,
    envIntensity: 0.35,
    particles: { type: 'embers', color: '#ff8a3a', size: 0.14 },
    ground: { color: '#4a4240', roughness: 0.9 },
    ballast: '#3b3432',
    surface: 'gravel',
  },
  space: {
    id: 'space',
    vehicle: 'rovers',
    track: 'metal',
    name: '太空基地',
    en: 'STAR BASE',
    swatch: ['#05060f', '#6f7cff'],
    sky: { horizon: '#1b2150', zenith: '#010208', glow: '#8fa0ff', sunDir: [-0.6, 0.35, -1], cloud: 0, stars: 1 },
    fog: { color: '#141836', near: 70, far: 320 },
    hemi: { sky: '#8a9cff', ground: '#2a2a35', intensity: 0.55 },
    sun: { color: '#ffffff', intensity: 2.7, offset: [-16, 22, 12] },
    exposure: 1.1,
    bloom: 0.8,
    envIntensity: 0.6,
    particles: null,
    ground: { color: '#a3a1a0', roughness: 0.95, tex: 'moon' },
    ballast: '#6d6c70',
    surface: 'sand',
  },
  underwater: {
    id: 'underwater',
    vehicle: 'subs',
    track: 'seabed',
    name: '海底世界',
    en: 'DEEP SEA',
    swatch: ['#0a2a4a', '#3fd0e0'],
    sky: { horizon: '#1f7a9c', zenith: '#06203a', glow: '#9fe8ff', sunDir: [0, 1, -0.3], cloud: 0, stars: 0 },
    fog: { color: '#1b6b8a', near: 22, far: 150 },
    hemi: { sky: '#9fe8ff', ground: '#1a3a4a', intensity: 0.95 },
    sun: { color: '#bff4ff', intensity: 1.8, offset: [0, 30, 4] },
    exposure: 1.05,
    bloom: 0.45,
    envIntensity: 0.5,
    particles: { type: 'bubbles', color: '#d8f6ff', size: 0.2 },
    ground: { color: '#d9c9a0', roughness: 1, tex: 'sand' },
    ballast: '#b8a984',
    surface: 'sand',
  },
  candy: {
    id: 'candy',
    vehicle: 'icecream',
    track: 'candy',
    name: '糖果王國',
    en: 'CANDY LAND',
    swatch: ['#ff9ad5', '#9be7ff'],
    sky: { horizon: '#ffe0f0', zenith: '#8fd3ff', glow: '#fff0a8', sunDir: [0.3, 0.4, -1], cloud: 0.7, stars: 0 },
    fog: { color: '#eab4d2', near: 70, far: 280 },
    hemi: { sky: '#fff0fa', ground: '#c77a9e', intensity: 0.95 },
    sun: { color: '#fff6f0', intensity: 2.3, offset: [-12, 26, 12] },
    exposure: 0.92,
    bloom: 0.28,
    envIntensity: 0.55,
    particles: { type: 'petals', color: '#ffe066', size: 0.14 },
    ground: { color: '#d98fb4', roughness: 0.8, tex: 'sand' },
    ballast: '#c9789f',
    surface: 'grass',
  },
  dino: {
    id: 'dino',
    vehicle: 'dinos',
    track: 'mud',
    name: '恐龍谷',
    en: 'DINO VALLEY',
    swatch: ['#5a7a2a', '#f6c870'],
    sky: { horizon: '#f6e2b8', zenith: '#5f9fd4', glow: '#ffcf80', sunDir: [0.4, 0.3, -1], cloud: 0.7, stars: 0 },
    fog: { color: '#d8d0a8', near: 45, far: 220 },
    hemi: { sky: '#e8f5d0', ground: '#5a4a2a', intensity: 1.1 },
    sun: { color: '#fff0d0', intensity: 3.0, offset: [-12, 26, 12] },
    exposure: 1.05,
    bloom: 0.45,
    envIntensity: 0.4,
    particles: { type: 'spores', color: '#fff2a0', size: 0.12 },
    ground: { color: '#8a7a4a', roughness: 0.95 },
    ballast: '#7a6a42',
    surface: 'grass',
  },
  halloween: {
    id: 'halloween',
    vehicle: 'pumpkins',
    track: 'graveyard',
    name: '南瓜鎮',
    en: 'SPOOKY TOWN',
    swatch: ['#1a0e24', '#ff8a1c'],
    sky: { horizon: '#4a2a5a', zenith: '#0b0614', glow: '#ff9a3c', sunDir: [-0.3, 0.35, -1], cloud: 0.5, stars: 0.8 },
    fog: { color: '#2a1a3a', near: 30, far: 170 },
    hemi: { sky: '#8a6ad0', ground: '#1a1020', intensity: 0.75 },
    sun: { color: '#b8c8ff', intensity: 1.3, offset: [10, 24, 8] },
    exposure: 1.2,
    bloom: 0.9,
    envIntensity: 0.4,
    particles: { type: 'spores', color: '#ffae3c', size: 0.14 },
    ground: { color: '#3a3530', roughness: 0.9 },
    ballast: '#2e2a26',
    surface: 'gravel',
  },
  skycity: {
    id: 'skycity',
    vehicle: 'airships',
    track: 'planks',
    name: '天空之城',
    en: 'SKY CITY',
    swatch: ['#3d8ee8', '#ffffff'],
    sky: { horizon: '#e8f6ff', zenith: '#3d8ee8', glow: '#fff6d0', sunDir: [-0.3, 0.4, -1], cloud: 0.6, stars: 0 },
    fog: { color: '#dcefff', near: 70, far: 300 },
    hemi: { sky: '#ffffff', ground: '#9fb6d6', intensity: 1.05 },
    sun: { color: '#fffaf0', intensity: 2.6, offset: [-12, 26, 12] },
    exposure: 0.95,
    bloom: 0.28,
    envIntensity: 0.5,
    particles: null,
    ground: { color: '#ffffff', roughness: 1, tex: 'snow' },
    ballast: '#e0e8f0',
    surface: 'wood',
  },
  bamboo: {
    id: 'bamboo',
    vehicle: 'pandas',
    track: 'stone',
    name: '熊貓竹林',
    en: 'PANDA FOREST',
    swatch: ['#2f6b2a', '#e6f2da'],
    sky: { horizon: '#e6f2da', zenith: '#7fb8d8', glow: '#fff3c0', sunDir: [0.3, 0.35, -1], cloud: 0.6, stars: 0 },
    fog: { color: '#d2e6c8', near: 40, far: 200 },
    hemi: { sky: '#eaf7e0', ground: '#4a5a3a', intensity: 1.15 },
    sun: { color: '#fff6e0', intensity: 2.8, offset: [-12, 26, 12] },
    exposure: 1.05,
    bloom: 0.4,
    envIntensity: 0.45,
    particles: { type: 'petals', color: '#8fcf6a', size: 0.2 },
    ground: { color: '#7a8a5a', roughness: 0.95 },
    ballast: '#6a7a4a',
    surface: 'grass',
  },
  // 地下鐵：白磁磚牆、日光燈、月台門
  japan: {
    id: 'japan',
    vehicle: 'metro',
    track: 'rail',
    name: '日本地鐵',
    en: 'TOKYO METRO',
    swatch: ['#f08c1c', '#e9ecef'],
    sky: { horizon: '#1c1e24', zenith: '#0d0e12', glow: '#000000', sunDir: [0, 1, 0], cloud: 0, stars: 0 },
    fog: { color: '#23262d', near: 35, far: 170 },
    hemi: { sky: '#e8eef8', ground: '#55565c', intensity: 1.0 },
    sun: { color: '#f2f6ff', intensity: 1.5, offset: [0, 30, 1] },
    exposure: 1.05,
    bloom: 0.5,
    envIntensity: 0.4,
    particles: null,
    ground: { color: '#7c7a76', roughness: 0.9 },
    ballast: '#6c6862',
    surface: 'gravel',
    noGantry: true,
    underground: true,
  },
  // 高雄環狀輕軌風格：草皮軌道、無架空線、港邊與椰子樹
  taiwan: {
    id: 'taiwan',
    vehicle: 'tram',
    track: 'rail',
    name: '台灣輕軌',
    en: 'HARBOR LRT',
    swatch: ['#12836b', '#bfe8ff'],
    sky: { horizon: '#d6efff', zenith: '#2f8fe0', glow: '#fff1c2', sunDir: [0.4, 0.5, -1], cloud: 0.5, stars: 0 },
    fog: { color: '#cfe6f2', near: 70, far: 320 },
    hemi: { sky: '#dff2ff', ground: '#6f8f58', intensity: 1.2 },
    sun: { color: '#fff4dc', intensity: 3.3, offset: [-12, 28, 10] },
    exposure: 1.02,
    bloom: 0.35,
    envIntensity: 0.5,
    particles: null,
    ground: { color: '#8cba62', roughness: 0.95 },
    ballast: '#5f9e3f',
    surface: 'grass',
    noGantry: true,
    noWires: true,
    grassTrack: true,
  },
};

export const THEME_ORDER = [
  'city', 'seaside', 'tunnel', 'snow', 'neon', 'desert', 'sakura', 'jungle',
  'volcano', 'space', 'underwater', 'candy', 'dino', 'halloween', 'skycity', 'bamboo',
  'japan', 'taiwan',
];
export const TOUR_LEN = 600; // 環遊模式：每 600 公尺換一個場景
